### ISSUE TITLE
Qsub Job array 

### ISSUE THREAD

**Issue by susan-sheehan** [TheJacksonLaboratory/Batch-Image-Analysis#2]
Hi Can you please take a look at this?  I am trying to use this code to run a job array.  I can run it as a single job by calling bash ilastikheadless.sh  where the code looks for a list of directories and then processes all the tif files in the directories.  now I want to set up the command such that it treats each directory as a new job in a job array.  yesterday I tried to run this command via "bash ilastikheadless_jobarray.sh"  the job ran but I don;t think the PBS commands worked as I never got a job ID so I think I ended up running it directly on the main node in cadillac.     I haven't looked at the output of yesterday's run yet but I suspect there might be some small issues with where I put the $PBS_ARRAYID etc in my code but what I would really like input on is if you see any issues with the first 6 lines of ilastikheadless_jobarray.sh and how I call the PBS commands.

**Comment by ytakemon** [comment]
You're probably looking for an array submission answer, but I would usually run this as multiple individual submissions. Mainly because I don't really know how job arrays work yet.
My solution would be to run lines 9 -13 directly on cadillac's main node, then use a for loop to submit each directory as a variable. 

so take this origianl lines 9-13 out of your script and run that portion on the main node. 
```
USERDATASHARE="/hpcdata/sms/GlomerularIdentification/"

cd $USERDATASHARE"/QSUB_IMAGE_DATA/132312M"
find . -type d -name "*" | sed 's/^\.\///' | xargs -n1 -I{} echo $PWD'/'{} | tail -n +2 > input_dir.list
input_dir.list=$PBS_ARRAYID`
```
then do something like this:
```
for i in ${input_dir.list[*]}
do
qsub -v input_dir=${i} ilastikheadless_jobarray.sh
done
```

you'll need to use ${input_dir} as a variable inside your ilastikheadless_jobarray.sh. This way you can feed it any list of directories. You could also just wrap that option up as a bash script, that you run directly on the head node as it doesn't take much computing power. That bash script would looks like this:

```
#!/bin/bash -l 
USERDATASHARE="/hpcdata/sms/GlomerularIdentification/"

cd $USERDATASHARE"/QSUB_IMAGE_DATA/132312M"
find . -type d -name "*" | sed 's/^\.\///' | xargs -n1 -I{} echo $PWD'/'{} | tail -n +2 > input_dir.list
input_dir.list=$PBS_ARRAYID

for i in ${input_dir.list[*]}
do
qsub -v input_dir=${i} ilastikheadless_jobarray.sh
done
```

**Comment by susan-sheehan** [comment]
Yeah, the problem is that I really need an array solution because I have over 600 Jobs each with thousands of files to submit due to the computation time and tracking involved. Your correct about ways to run it not as a job array I have that part working

**Comment by susan-sheehan** [comment]
I have this working
